;
; AssemblerApplication1.asm
;
; Created: 7/6/2016 1:52:00 PM
; Author : Chris
;

main:
	ldi r16, 0xFF
	ldi r17, 0x00
	OUT DDRB, r16
	ldi  r18, 82
    ldi  r19, 41
    ldi  r20, 174

	loop:
	OUT PINB, r16
	rjmp L1
	OUT PINB, r17
	rjmp loop

; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Delay 62 497 cycles
; 499ms 976us at .125 MHz
; Constants needed above
;    ldi  r18, 82
;    ldi  r19, 41
L1: dec  r19
    brne L1
    dec  r18
    brne L1
    nop
